[tool.poetry]
name = "UT3DataBrowser"
version = "0.1.0"
description = "A user interface to browse data taken at UT3"
authors = ["Reinier van Mourik <reinier.vanmourik@tausystems.com>"]
readme = "README.md"
packages = [
    {include = "ut3_data_browser"},
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"

flask = "2.0.*"
werkzeug = "2.0.*"   # flask's dependency is Werkzeug >=2.0, but >=2.1 is actually incompatible 
flask-wtf = "^1.2.1"
python-decouple = "^3.8"
bootstrap-flask = "^2.3.3"
platformdirs = "^4.1.0"

sqlalchemy = "^2.0.25"
psycopg2 = "^2.9.9"
matplotlib = "^3.9.2"
tifffile = "^2024.9.20"
toml = "^0.10.2"
